CREATE TABLE `CAR` (
	`CAR_PK`	VARCHAR(30)	NOT NULL,
	`COMPANY`	VARCHAR(30)	NULL,
	`CAR_NAME`	VARCHAR(30)	NULL,
	`AGE`	INT	NULL
);

CREATE TABLE `OPTIONS` (
	`OPTION_PK`	VARCHAR(30)	NOT NULL,
	`OPTIONS`	VARCHAR(30)	NULL
);

CREATE TABLE `CAR_OPTION` (
	`CAR_PK`	VARCHAR(30)	NOT NULL,
	`OPTION_PK`	VARCHAR(30)	NOT NULL,
    'CAR_NAME' VARCHAR(30),
    'AGE' INT,
    'OPTIONS' VARCHAR(30)
);

ALTER TABLE `CAR` ADD CONSTRAINT `PK_CAR` PRIMARY KEY (
	`CAR_PK`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`OPTION_PK`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `PK_CAR_OPTION` PRIMARY KEY (
	`CAR_PK`,
	`OPTION_PK`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_CAR_TO_CAR_OPTION_1` FOREIGN KEY (
	`CAR_PK`
)
REFERENCES `CAR` (
	`CAR_PK`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_OPTION_TO_CAR_OPTION_1` FOREIGN KEY (
	`OPTION_PK`
)
REFERENCES `OPTION` (
	`OPTION_PK`
);

