CREATE TABLE `CAR` (
	`CAR_PK`	VARCHAR(30)	NOT NULL,
	`CAR_NAME`	VARCHAR(30)	NULL,
	`COMPANY`	VARCHAR(30)	NULL,
	`AGE`	INT	NULL
);

CREATE TABLE `OPTION` (
	`OPTION_PK`	VARCHAR(30)	NOT NULL,
	`CAR_FK`	VARCHAR(30)	NOT NULL,
	`OPTION`	VARCHAR(100)	NULL
);

ALTER TABLE `CAR` ADD CONSTRAINT `PK_CAR` PRIMARY KEY (
	`CAR_PK`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`OPTION_PK`,
	`CAR_FK`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `FK_CAR_TO_OPTION_1` FOREIGN KEY (
	`CAR_FK`
)
REFERENCES `CAR` (
	`CAR_PK`
);

